name: Resources
on:
  schedule:
  - cron: "0 0 * * 0"
permissions:
    contents: write
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'
            - run: npm install
            - run:  npm run data

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: |
                      countryData/data/providers/IMF.json
                      countryData/data/allCountriesBaseData.json
                      countryData/data/allCountriesData.json
                      countryData/data/countryList.json
                  commit-msg: Update resources
                  allow-dot: true
                  allow-removing: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
